# Generated by Django 4.0.6 on 2022-08-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='审批者')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '待审批'), (2, '通过'), (3, '不通过')], verbose_name='状态')),
                ('create_datetime', models.DateTimeField(verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='app01.userinfo', verbose_name='审批者')),
                ('tpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.template', verbose_name='模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app01.userinfo', verbose_name='发起者')),
            ],
        ),
    ]
