# Generated by Django 4.0.6 on 2022-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_template_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('avatar', models.FileField(upload_to='xxxx/', verbose_name='头像')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待审批'), (2, '通过'), (3, '不通过')], default=1, verbose_name='状态'),
        ),
    ]
