# Generated by Django 4.0.6 on 2022-08-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_info_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.TextField(max_length=32, verbose_name='姓名'),
        ),
    ]
